# -*- coding: utf-8 -*-
"""Nested Loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mr648gDfaNAJkYPCFwNTXgc-abr8pGTM
"""

# Print the first pattern
rows = int(input("Enter the number of rows: "))
print("\nPattern 5:")
for i in range(1, rows + 1):
    for j in range(i):
        print("*", end="")
    print()

rows = int(input("Enter the number of rows: "))
print("\nPattern 5:")
for i in range(rows, 0, -1):
    for j in range(i):
        print("*", end="")
    print()

rows = int(input("Enter the number of rows: "))
print("\nPattern 5:")
for i in range(rows):
    for j in range(rows - i - 1):
        print(" ", end="")
    for j in range(i + 1):
        print("*", end="")
    print()

rows = int(input("Enter the number of rows: "))
print("\nPattern 5:")
for i in range(rows, 0, -1):
    for j in range(rows - i):
        print(" ", end="")
    for j in range(i):
        print("*", end="")
    print()

# Get the number of rows from the user
n = int(input("Enter the number of rows: "))

print("\nPattern 5:")
for i in range(n, 0, -1):
    for j in range(1, i + 1):
        print((i + j) % 2, end="")
    print()

print('-' * 20)

rows = int(input("Enter the number of rows: "))
print("\nPattern 5:")
for i in range(rows, 0, -1):
    for j in range(rows - i):
        print(" ", end="")
    for j in range(2 * i - 1):
        print("*", end="")
    print()