# -*- coding: utf-8 -*-
"""String Methods

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7EbnKcjKv5gO78d0DSP9-XMGC7VcVQs

# 1. Write a Python program to Count all letters, digits, and special symbols from the given string Input = “P@#yn26at^&i5ve” Output: Chars = 8 Digits = 2 Symbol = 3
"""

# 1. Count all letters, digits, and special symbols
def count_chars(string):
    chars = 0
    digits = 0
    symbols = 0

    for char in string:
        if char.isalpha():
            chars += 1
        elif char.isdigit():
            digits += 1
        else:
            symbols += 1

    return chars, digits, symbols

input_string = "P@#yn26at^&i5ve"
chars, digits, symbols = count_chars(input_string)
print("Chars =", chars, "Digits =", digits, "Symbols =", symbols)

"""
# 2. Write a Python program to remove duplicate characters of a given string. Input = “String and String Function” Output: String and Function


"""

# 2. Remove duplicate characters
def remove_duplicates(string):
    seen = set()
    result = ""
    for char in string:
        if char not in seen:
            seen.add(char)
            result += char
    return result

input_string = "String and String Function"
result = remove_duplicates(input_string)
print(result)

"""# 3. Write a Python program to count Uppercase, Lowercase, special character and numeric values in a given string Input = “Hell0 W0rld ! 123 * # welcome to pYtHoN” Output: UpperCase : 5 LowerCase : 18 NumberCase : 5 SpecialCase : 1"""

# 3. Count Uppercase, Lowercase, special character and numeric values
def count_char_types(string):
    uppercase = 0
    lowercase = 0
    special_chars = 0
    numeric_values = 0

    for char in string:
        if char.isupper():
            uppercase += 1
        elif char.islower():
            lowercase += 1
        elif char.isdigit():
            numeric_values += 1
        else:
            special_chars += 1

    return uppercase, lowercase, special_chars, numeric_values

input_string = "Hell0 W0rld ! 123 * # welcome to pYtHoN"
uppercase, lowercase, special_chars, numeric_values = count_char_types(input_string)
print("UpperCase:", uppercase, "LowerCase:", lowercase, "NumberCase:", numeric_values, "SpecialCase:", special_chars)

"""
# 4. Write a Python Count vowels in a string input= “Welcome to Python Assignment” Output: Total vowels are: 8
"""

def count_vowels(s):
    vowels = 'aeiouAEIOU'
    count = sum(1 for char in s if char in vowels)
    print(f"Total vowels are: {count}")

# Test the function
input_string = "Welcome to Python Assignment"
count_vowels(input_string)